### ISSUE TITLE
Run a base-line test with Long-range dependencies

### ISSUE THREAD

**Issue by Cortexelus** [wilile26811249/Fastformer-PyTorch#2]
A common [criticism](https://www.reddit.com/r/MachineLearning/comments/p9s03l/fastformer_additive_attention_is_all_you_need/) of this paper was the lack of LRA baselines (long-range dependencies):

Would be awesome to see how it compares to other transformers in that regard.

**Comment by zh-plus** [comment]
Unfortunately, this is an unofficial implementation...
