### ISSUE TITLE
How to Mask ?

### ISSUE THREAD

**Issue by xesdiny** [wilile26811249/Fastformer-PyTorch#3]
How to mask the subword & padding infos in this attention if I want to use it in GPT?

**Comment by wilile26811249** [comment]
https://github.com/wilile26811249/Fastformer-PyTorch/blob/2ab9db4c87209046b24c5cb047d4d4849679cf3d/Fastformer.py#L25~L36

@xesdiny 
Sorry, I missed the part. It is already updated, please check. Thank you.

**Comment by xesdiny** [comment]
Emm,I can't understand that the `global_key` just mask in `decode_dim`.what's mean?
And I think the mask method is not effective on sequence tasks.
By the way.Are you sure that the `masked_fill`  will work? 
```
mask_value = torch.finfo(x.dtype).min
...
global_key = p * beta_weight
```
The Element-wise  product will all Nan in `result`.

**Comment by wilile26811249** [comment]
@xesdiny 
Yes, the result are all NaN.
I fix the error about the implement of the mask part.
Can you check again? Thank you.
