### ISSUE TITLE
What is your version of PyTorch ? 

### ISSUE THREAD

**Issue by learningelectric** [wilile26811249/Fastformer-PyTorch#5]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
C:\Users\ADMINI~1\AppData\Local\Temp/ipykernel_21240/4222065097.py in <module>
----> 1 model = Fastformer(dim = 3, decode_dim = 8)
      2 x = torch.randn(4, 6, 3)
      3 mask = torch.ones(1, 8).bool()
      4 result = model(x, mask)
      5 print(result.size())

TypeError: 'module' object is not callable
--------------------------------------------------------------------------------
my version is 1.9.0

**Comment by learningelectric** [comment]
I have found a way to solve it.
-------------------------------------------------------------------------------------
import torch
from Fastformer import Fastformer
model = Fastformer(dim = 3, decode_dim = 8)
x = torch.randn(4, 6, 3)
mask = torch.ones(1, 8).bool()
result = model(x, mask)
print(result.size())
--------------------------------------------------------------------------------------

**Comment by wilile26811249** [comment]
> ## I have found a way to solve it.
> ## import torch
> from Fastformer import Fastformer
> model = Fastformer(dim = 3, decode_dim = 8)
> x = torch.randn(4, 6, 3)
> mask = torch.ones(1, 8).bool()
> result = model(x, mask)
> print(result.size())

Thank you for your nortfication. I have already update the correct import.
